export type SupportedLocale = "zh-cn" | "zh-tw" | "en";

export const phrasesByLocale: Record<SupportedLocale, string[]> = {
  "zh-cn": [
    "人民对美好生活的向往，就是我们的奋斗目标。人世间的一切幸福都需要靠辛勤的劳动来创造。我们的责任，就是要团结带领全党全国各族人民，继续解放思想，坚持改革开放，不断解放和发展社会生产力，努力解决群众的生产生活困难，坚定不移走共同富裕的道路。",
    "我们的责任，就是要团结带领全党全国各族人民，接过历史的接力棒，继续为实现中华民族伟大复兴而努力奋斗。",
    "面对浩浩荡荡的时代潮流，面对人民群众过上更好生活的殷切期待，我们不能有丝毫自满，不能有丝毫懈怠，必须再接再厉、一往无前，继续把中国特色社会主义事业推向前进，继续为实现中华民族伟大复兴的中国梦而努力奋斗。",
    "我们正在从事的事业是伟大的，坚忍不拔才能胜利，半途而废必将一事无成。",
    "我们的蓝图是宏伟的，我们的奋斗必将是艰巨的。全党全国各族人民要团结一心，集思广益用好机遇，众志成城应对挑战，立行立改破解难题，奋发有为进行创新，让国家发展和人民生活一年比一年好。",
    "现在，大家都在讨论中国梦，我以为，实现中华民族伟大复兴，就是中华民族近代以来最伟大的梦想。这个梦想，凝聚了几代中国人的夙愿，体现了中华民族和中国人民的整体利益，是每一个中华儿女的共同期盼。",
    "空谈误国，实干兴邦。我们这一代共产党人一定要承前启后、继往开来，把我们的党建设好，团结全体中华儿女把我们国家建设好，把我们民族发展好，继续朝着中华民族伟大复兴的目标奋勇前进。",
    "历史告诉我们，每个人的前途命运都与国家和民族的前途命运紧密相连。国家好，民族好，大家才会好。实现中华民族伟大复兴是一项光荣而艰巨的事业，需要一代又一代中国人共同为之努力。",
    "检验我们一切工作的成效，最终都要看人民是否真正得到了实惠，人民生活是否真正得到了改善，这是坚持立党为公、执政为民的本质要求，是党和人民事业不断发展的重要保证。",
    "崇高信仰始终是我们党的强大精神支柱，人民群众始终是我们党的坚实执政基础。只要我们永不动摇信仰、永不脱离群众，我们就能无往而不胜。",
    "我们的党是全心全意为人民服务的政党。党领导人民已经取得举世瞩目的成就，我们完全有理由因此而自豪，但我们自豪而不自满，决不会躺在过去的功劳簿上。",
    "打铁还需自身硬。我们的责任，就是同全党同志一道，坚持党要管党、从严治党，切实解决自身存在的突出问题，切实改进工作作风，密切联系群众，使我们党始终成为中国特色社会主义事业的坚强领导核心。",
    "人民群众是我们力量的源泉。我们深深知道，每个人的力量是有限的，但只要我们万众一心、众志成城，就没有克服不了的困难；每个人的工作时间是有限的，但全心全意为人民服务是无限的。",
    "责任重于泰山，事业任重道远。我们一定要始终与人民心心相印、与人民同甘共苦、与人民团结奋斗，夙夜在公，勤勉工作，努力向历史、向人民交出一份合格的答卷。",
    "坚定理想信念，坚守共产党人精神追求，始终是共产党人安身立命的根本。对马克思主义的信仰，对社会主义和共产主义的信念，是共产党人的政治灵魂，是共产党人经受住任何考验的精神支柱。",
    "形象地说，理想信念就是共产党人精神上的'钙'，没有理想信念，理想信念不坚定，精神上就会'缺钙'，就会得'软骨病'。",
    "物必先腐，而后虫生。近年来，一些国家因长期积累的矛盾导致民怨载道、社会动荡、政权垮台，其中贪污腐败就是一个很重要的原因。大量事实告诉我们，腐败问题越演越烈，最终必然会亡党亡国！我们要警醒啊！",
    "要坚持党的群众路线，坚持人民主体地位，时刻把群众安危冷暖放在心上，及时准确了解群众所思、所盼、所忧、所急，把群众工作做实、做深、做细、做透。",
    "我们要与人民心心相印、与人民同甘共苦、与人民团结奋斗。现在我们谈不上说一块苦，但一定要一块过、一块干，保持和发扬党的光荣传统和优良作风，保持同人民群众的血肉联系，切实把工作做好。",
    "规定就是规定，不加'试行'两字，就是要表明一个坚决的态度，表明这个规定是刚性的。我们说了不是白说，说了就必须做到，把文件上写的内容一一落到实处。",
    "对各类困难群众，我们要格外关注、格外关爱、格外关心，时刻把他们的安危冷暖放在心上，关心他们的疾苦，千方百计帮助他们排忧解难。",
    "郑板桥有一首诗写道：'衙斋卧听萧萧竹，疑是民间疾苦声。些小吾曹州县吏，一枝一叶总关情。'我们共产党人对人民群众的疾苦更要有这样的情怀，要有仁爱之心、关爱之心，更多关注困难群众，不断提高全体人民生活水平。",
    "多想想我们干的事情是不是党和人民需要我们干的？要一心一意为老百姓做事，心里装着困难群众，多做雪中送炭的工作，常去贫困地区走一走，常到贫困户家里坐一坐，常同困难群众聊一聊，多了解困难群众的期盼，多解决困难群众的问题，满怀热情为困难群众办事。",
    "领导不是百事通，不是万能的。要做群众的先生，先做群众的学生。领导干部要放下架子，甘当小学生，多同群众交朋友，多向群众请教。要真正悟透群众是真正的英雄。",
    "大量事实证明，一个地方的工作，成在干部作风，败也在干部作风；一个地方的事业，兴在干部作风，衰也在干部作风。",
    "下去调研，要去一些困难多的地方、问题多的地方，调研不是光看好的。看了困难多、问题多的地方，才能帮助他们解决问题，也有利于我们正确决策。",
    "领导干部是人民的公仆，必须始终牢记宗旨、牢记责任，自觉把权力行使的过程作为为人民服务的过程，自觉接受人民监督，做到为民用权、公正用权、依法用权、廉洁用权。",
    "实干兴邦，空谈误国。这个道理，我们都要牢记在心。各级领导干部要坚持为民务实清廉，切实转变工作作风，做到讲实话、干实事，敢作为、勇担当，言必信、行必果。",
    "政贵有恒。为官一方，为政一时，既要大胆开展工作、锐意进取，又要保持大局稳定和工作连续性。真正做到一张好的蓝图一干到底，不折腾，不反复，切实干出成效来。",
    "改革开放是决定当代中国命运的关键一招，也是决定实现'两个一百年'奋斗目标、实现中华民族伟大复兴的关键一招。",
    "我国改革已经进入攻坚期和深水区，我们必须以更大的政治勇气和智慧，不失时机深化重要领域改革。改革开放中的矛盾只能用改革开放的办法来解决。",
    "我国改革已经进入攻坚期和深水区，进一步深化改革，必须坚定信心、凝聚共识、统筹谋划、协同推进。改革开放也是无止境的。停顿和倒退没有出路。",
    "唯改革者进，唯创新者强，唯改革创新者胜。",
    "推出一批能叫得响、立得住、群众认可的硬招实招，处理好改革'最先一公里'和'最后一公里'的关系，突破'中梗阻'，防止不作为，把改革方案的含金量充分展示出来，让人民群众有更多获得感。",
    "改革开放是前无古人的崭新事业，必须坚持正确的方法论，在不断实践探索中推进。摸着石头过河，是富有中国特色、符合中国国情的改革方法。",
    "改革要抓铁有痕、踏石留印，不能搞改革'弄虚作假'，要增强改革的系统性、整体性、协同性。",
    "改革遵循渐进性规律，要稳扎稳打、步步为先，既要敢于突破，又要一步一个脚印、稳扎稳打向前走，确保实现改革的目标任务。",
    "对改革进程中已经出现和可能出现的问题，困难要一个一个克服，问题要一个一个解决，既敢于出招又善于应招，做到蹄疾步稳、砥砺前行。",
    "改革开放只有进行时、没有完成时。没有改革开放，就没有中国的今天，也就没有中国的明天。",
    "人生在勤，勤则不匮。幸福不会从天降，美好生活靠劳动创造。全面建成小康社会的奋斗目标，为广大劳动群众指明了光明的未来。",
    "志之所趋，无远弗届，穷山距海，不能限也。对想做爱做的事要敢试敢为，努力从无到有、从小到大，把理想变为现实。要敢于做先锋，而不做过客、当看客，让创新成为青春远航的动力，让创业成为青春搏击的能量。",
    "为有牺牲多壮志，敢教日月换新天。要奋斗就会有牺牲，我们要始终发扬大无畏精神和无私奉献精神。奋斗者是精神最为富足的人，也是最懂得幸福、最享受幸福的人。",
    "面对复杂变化的世界，人类社会向何处去？亚洲前途在哪里？我认为，回答这些时代之问，我们要不畏浮云遮望眼，善于拨云见日，把握历史规律，认清世界大势。",
    "宝剑锋从磨砺出，梅花香自苦寒来。人类的美好理想，都不可能唾手可得，都离不开筚路蓝缕、手胼足胝的艰苦奋斗。我们的国家，我们的民族，从积贫积弱一步一步走到今天的发展繁荣，靠的就是一代又一代人的顽强拼搏，靠的就是中华民族自强不息的奋斗精神。",
    "实现我们的发展目标，实现中国梦，必须增强道路自信、理论自信、制度自信，千磨万击还坚劲，任尔东南西北风。",
    "功崇惟志，业广惟勤。我国仍处于并将长期处于社会主义初级阶段，实现中国梦，创造全体人民更加美好的生活，任重而道远，需要我们每一个人继续付出辛勤劳动和艰苦努力。",
    "积土而为山，积水而为海。幸福和美好未来不会自己出现，成功属于勇毅而笃行的人。",
    "芳林新叶催陈叶，流水前波让后波。改革开放40年来，我们以敢闯敢干的勇气和自我革新的担当，闯出了一条新路、好路，实现了从'赶上时代'到'引领时代'的伟大跨越。",
    "建立中国共产党、成立中华人民共和国、推进改革开放和中国特色社会主义事业，是五四运动以来我国发生的三大历史性事件，是近代以来实现中华民族伟大复兴的三大里程碑。",
    "我国社会大局保持长期稳定，成为世界上最有安全感的国家之一。忍饥挨饿、缺吃少穿、生活困顿这些几千年来困扰我国人民的问题总体上一去不复返了！",
    "40年来取得的成就不是天上掉下来的，更不是别人恩赐施舍的，而是全党全国各族人民用勤劳、智慧、勇气干出来的！我们用几十年时间走完了发达国家几百年走过的工业化历程。在中国人民手中，不可能成为了可能。",
    "改革开放40年来，我们党全部理论和实践的主题是坚持和发展中国特色社会主义。在中国这样一个有着5000多年文明史、13亿多人口的大国推进改革发展，没有可以奉为金科玉律的教科书，也没有可以对中国人民颐指气使的教师爷。",
    "改什么、怎么改必须以是否符合完善和发展中国特色社会主义制度、推进国家治理体系和治理能力现代化的总目标为根本尺度，该改的、能改的我们坚决改，不该改的、不能改的坚决不改。",
    "实现祖国完全统一，是全体中华儿女共同心愿，是中华民族根本利益所在。我们有坚定的政治决心和强大能力维护国家主权和领土完整，祖国的神圣领土一寸都不能分裂出去！",
    "事者，生于虑，成于务，失于傲。伟大梦想不是等得来、喊得来的，而是拼出来、干出来的。我们现在所处的，是一个船到中流浪更急、人到半山路更陡的时候，是一个愈进愈难、愈进愈险而又不进则退、非进不可的时候。",
    "信仰、信念、信心，任何时候都至关重要。小到一个人、一个集体，大到一个政党、一个民族、一个国家，只要有信仰、信念、信心，就会愈挫愈奋、愈战愈勇，否则就会不战自败、不打自垮。",
    "在近代以来漫长的历史进程中，中国人民经历了太多太多的磨难，付出了太多太多的牺牲，进行了太多太多的拼搏。现在，中国人民和中华民族在历史进程中积累的强大能量已经充分爆发出来了，为实现中华民族伟大复兴提供了势不可挡的磅礴力量。",
    "建成社会主义现代化强国，实现中华民族伟大复兴，是一场接力跑，我们要一棒接着一棒跑下去，每一代人都要为下一代人跑出一个好成绩。",
    "中国特色社会主义不是从天上掉下来的，而是在改革开放40年的伟大实践中得来的，是在中华人民共和国成立近70年的持续探索中得来的，是在我们党领导人民进行伟大社会革命97年的实践中得来的，是党和人民历经千辛万苦、付出各种代价取得的宝贵成果。",
    "新时代坚持和发展中国特色社会主义，需要大批能把马克思主义中国化讲好的人才，讲人民群众听得懂、听得进的话语，让党的创新理论'飞入寻常百姓家'。",
    "不忘初心、牢记使命，必须发扬斗争精神，勇于担当作为。我们党诞生于国家内忧外患、民族危难之时，一出生就铭刻着斗争的烙印，一路走来就是在斗争中求得生存、获得发展、赢得胜利。",
    "我们讲的斗争，不是为了斗争而斗争，也不是为了一己私利而斗争，而是为了实现人民对美好生活的向往、实现中华民族伟大复兴知重负重、苦干实干、攻坚克难。",
    "衡量党员、干部有没有斗争精神、是不是敢于担当，就要看面对大是大非敢不敢亮剑、面对矛盾敢不敢迎难而上、面对危机敢不敢挺身而出、面对失误敢不敢承担责任、面对歪风邪气敢不敢坚决斗争。",
    "心有所信，方能行远。面向未来，走好新时代的长征路，我们更需要坚定理想信念、矢志拼搏奋斗。",
    "实践告诉我们，伟大事业都始于梦想。梦想是激发活力的源泉。在建成社会主义现代化强国、实现中华民族伟大复兴的征途上，每一个行业、每一个人都要心怀梦想、奋勇拼搏，一步一个脚印，一棒接着一棒，在奋力奔跑和接续奋斗中成就梦想。",
    "世界上最大的幸福莫过于为人民幸福而奋斗。心中装着百姓，手中握有真理，脚踏人间正道，我们信心十足、力量十足。",
    "中国梦是两岸同胞共同的梦，民族复兴、国家强盛，两岸中国人才能过上富足美好的生活。在中华民族走向伟大复兴的进程中，台湾同胞定然不会缺席。",
    "爱国主义是中华民族的民族心、民族魂。我们要把学习的具体目标同民族复兴的宏大目标结合起来，为之而奋斗。只有把小我融入大我，才会有海一样的胸怀，山一样的崇高。",
    "我们推动媒体融合发展，是要做大做强主流舆论，巩固全党全国人民团结奋斗的共同思想基础，为实现'两个一百年'奋斗目标、实现中华民族伟大复兴的中国梦提供强大精神力量和舆论支持。",
    "我们在扶贫脱贫方面取得的成就和经验，为全球减贫事业贡献了中国智慧和中国方案，彰显了中国共产党领导和我国社会主义制度的政治优势。在发展中国家中，只有中国实现了快速发展和大规模减贫同步，这是一个了不起的人间奇迹。",
    "今天，在中国共产党领导下，我们开辟了中国特色社会主义道路，形成了中国特色社会主义理论体系，建立了中国特色社会主义制度，发展了中国特色社会主义文化，推动中国特色社会主义进入了新时代。中国人民拥有了前所未有的道路自信、理论自信、制度自信、文化自信，中华民族伟大复兴展现出前所未有的光明前景！",
    "中国特色社会主义进入新时代，我们比历史上任何时期都更接近、更有信心和能力实现中华民族伟大复兴。我们千万不能在一片喝彩声、赞扬声中丧失革命精神和斗志，逐渐陷入安于现状、不思进取、贪图享乐的状态，而是要牢记船到中流浪更急、人到半山路更陡。",
    "要引导人们树立正确的历史观、国家观、民族观、文化观，不断巩固各族人民对伟大祖国的认同、对中华民族的认同、对中国特色社会主义道路的认同。",
    "我们既要坚信中国的发展前途光明，又要充分认识到道路曲折、困难很多，发挥中国共产党领导和我国社会主义制度的政治优势，集中力量办大事，打好防范和抵御风险的有准备之战，打好化险为夷、转危为机的战略主动战。",
    "要充分发挥集中力量办大事的制度优势和超大规模的市场优势，打好产业基础高级化、产业链现代化的攻坚战。",
    "马克思主义产生和发展、社会主义国家诞生和发展的历程充满着斗争的艰辛。建立中国共产党、成立中华人民共和国、实行改革开放、推进新时代中国特色社会主义事业，都是在斗争中诞生、在斗争中发展、在斗争中壮大的。",
    "当今世界正处于百年未有之大变局，我们党领导的伟大斗争、伟大工程、伟大事业、伟大梦想正在如火如荼进行，胜利实现我们党确定的目标任务，必须发扬斗争精神，增强斗争本领。",
    "新时代中国特色社会主义是我们党领导人民进行伟大社会革命的成果，也是我们党领导人民进行伟大社会革命的继续，必须一以贯之进行下去。一场社会革命要取得最终胜利，往往需要一个漫长的历史过程。",
    "我国疫情防控和复工复产之所以能够有力推进，根本原因是党的领导和我国社会主义制度的优势发挥了无可比拟的重要作用。发展环境越是严峻复杂，越要坚定不移深化改革，健全各方面制度，完善治理体系，善于运用制度优势应对风险挑战冲击。",
    "我们党之所以能够完成近代以来各种政治力量不可能完成的艰巨任务，带领人民取得革命、建设、改革的辉煌成就，就在于始终把马克思主义作为行动指南，始终坚持用马克思主义中国化最新成果武装全党，使全党始终保持统一的思想、坚定的意志、协调的行动、强大的战斗力。",
    "要注重提高马克思主义理论水平，学深悟透，融会贯通，掌握辩证唯物主义和历史唯物主义，掌握贯穿其中的马克思主义立场观点方法，掌握中国化的马克思主义，做马克思主义的坚定信仰者、忠实实践者。",
    "思政课要解决学生理想信念问题。要让有信仰的人讲信仰。对马克思主义的信仰，对社会主义和共产主义的信念，只有首先在思政课教师心中扎下根，才能在学生心中开花结果。",
    "要教育引导学生多读读马克思主义经典著作、当代中国马克思主义理论著作、中华优秀传统文化典籍等。要开出书单、指出重点，让学生正确理解经典著作，掌握马克思主义精髓，感知中华文化魅力。",
    "绳短不能汲深井，浅水难以负大舟。对领导干部来说，把握全局、谋划发展的战略能力是十分重要的。形成和提升这方面的能力，就要全面掌握辩证唯物主义和历史唯物主义的世界观和方法论。",
    "要把课堂教学和实践教学有机结合起来，充分运用丰富的历史文化资源，紧密联系中国共产党和中国人民的奋斗历程，深刻领悟马克思主义中国化的内在道理，深刻领悟为什么历史和人民选择了中国共产党和社会主义，进一步坚定'四个自信'。",
    "疫情发生以来，包括军队在内的广大医务工作者发扬特别能吃苦、特别能战斗的精神，义无反顾奔赴湖北和武汉，毫无畏惧投入防控救治工作，同时间赛跑，与病魔较量，你们真正做到了救死扶伤、大爱无疆。你们是光明的使者、希望的使者，是最美的天使，是真正的英雄！党和人民感谢你们！",
    "在中国共产党的坚强领导下，充分发挥中国特色社会主义制度优势，紧紧依靠人民群众，坚定信心、同舟共济、科学防治、精准施策，我们完全有信心、有能力打赢这场疫情防控阻击战。",
    "确保人民群众生命安全和身体健康，是我们党治国理政的一项重大任务。这次抗击新冠肺炎疫情，是对国家治理体系和治理能力的一次大考。",
    "我们要在全社会大力弘扬伟大抗疫精神，使之转化为全面建设社会主义现代化国家、实现中华民族伟大复兴的强大力量。",
    "历史和现实都告诉我们，只要不断解放和发展社会生产力，不断增强经济实力、科技实力、综合国力，不断让广大人民的获得感、幸福感、安全感日益充实起来，不断让坚持和发展中国特色社会主义、实现中华民族伟大复兴的物质基础日益坚实起来，我们就一定能够使中国特色社会主义航船乘风破浪、行稳致远。",
    "中国人民抗日战争胜利75年来，中国发生了翻天覆地的变化。中国共产党团结带领全国各族人民发愤图强、艰苦创业，创造了举世瞩目的发展成就，成功开辟了中国特色社会主义道路，中国特色社会主义进入新时代，脱贫攻坚战、全面建成小康社会胜利在望，中华民族伟大复兴迎来了光明前景。",
    "中国人民在抗日战争的壮阔进程中孕育出伟大抗战精神，向世界展示了天下兴亡、匹夫有责的爱国情怀，视死如归、宁死不屈的民族气节，不畏强暴、血战到底的英雄气概，百折不挠、坚忍不拔的必胜信念。伟大抗战精神，是中国人民弥足珍贵的精神财富，将永远激励中国人民克服一切艰难险阻、为实现中华民族伟大复兴而奋斗。",
    "你们今天是小树苗，将来要长成参天大树，中华民族伟大复兴的中国梦将在你们身上实现。希望同学们把红色基因传承好，好好学习知识和本领，努力成长为德智体美劳全面发展的社会主义建设者和接班人。",
    "党的十八大以来，我们着眼于实现中华民族伟大复兴中国梦，围绕实现党在新时代的强军目标，提出一系列重大方针原则，作出一系列重大决策部署，推进一系列重大工作，开创了强军事业新局面。",
    "推动我国汽车制造业高质量发展，必须加强关键核心技术和关键零部件的自主研发，实现技术自立自强，做强做大民族品牌。当今世界制造业竞争激烈，要抢抓机遇，大力发展战略性新兴产业，实现弯道超车。",
    "新时代坚持和发展中国特色社会主义，要全面贯彻新发展理念，坚持统筹推进'五位一体'总体布局、协调推进'四个全面'战略布局，加强顶层设计和战略布局，增强发展的整体性、协同性。",
    "面对新形势新任务，必须全面贯彻新时代党的治藏方略，铸牢中华民族共同体意识，提升发展质量，保障和改善民生，推进生态文明建设，加强党的组织和政权建设，确保国家安全和长治久安。",
    "新形势需要新担当、呼唤新作为。新时代经济特区建设要高举中国特色社会主义伟大旗帜，从我国进入新发展阶段大局出发，落实新发展理念，紧扣推动高质量发展、构建新发展格局，以一往无前的奋斗姿态、风雨无阻的精神状态，改革不停顿，开放不止步，在更高起点上推进改革开放。",
    "铭记伟大胜利，推进伟大事业，必须坚持推进经济社会发展，不断壮大我国综合国力。落后就要挨打，发展才能自强。只要我们统筹推进'五位一体'总体布局、协调推进'四个全面'战略布局，坚定不移贯彻新发展理念，构建新发展格局，就一定能够实现更高质量、更有效率、更加公平、更可持续、更为安全的发展，不断创造让世界惊叹的更大奇迹！",
    "党的十八大以来，我们党关于生态文明建设的思想不断丰富和完善。在'五位一体'总体布局中生态文明建设是其中一位，在新时代坚持和发展中国特色社会主义基本方略中坚持人与自然和谐共生是其中一条基本方略，在新发展理念中绿色是其中一大理念，在三大攻坚战中污染防治是其中一大攻坚战。",
    "实施扩大内需战略，是当前应对疫情冲击的需要，是保持我国经济长期持续健康发展的需要，也是满足人民日益增长的美好生活的需要。",
    "消费是我国经济增长的重要引擎，中等收入群体是消费的重要基础。目前，我国约有4亿中等收入人口，绝对规模世界最大。要把扩大中等收入群体规模作为重要政策目标，使更多普通劳动者通过自身努力进入中等收入群体。",
    "制造业是国家经济命脉所系。国有大型企业要发挥主力军作用，在抓好常态化疫情防控的前提下，带动上下游产业和中小企业全面复工复产。",
    "长期以来，山西兴于煤、困于煤，一煤独大导致产业单一。建设转型综合改革示范区，是党中央赋予山西的一项重大任务。山西要有紧迫感，更要有长远战略谋划，正确的就要坚持下去，久久为功，不要反复、不要折腾，争取早日蹚出一条转型发展的新路子。",
    "要更加及时有效解决企业恢复生产经营面临的各种困难和问题，把扩大内需各项政策举措抓实，把实体经济特别是制造业做强做优，持续推动产业结构调整优化，大力加强科技创新，在新基建、新技术、新材料、新装备、新产品、新业态上不断取得突破。",
    "我们要坚持一个中国原则和'九二共识'，巩固和发展两岸关系和平发展的基础，深化两岸经济文化交流合作，造福两岸同胞。台湾问题因民族弱乱而产生，必将随着民族复兴而终结！",
    "当前形势下，办好思政课，要从坚持和发展中国特色社会主义、建设社会主义现代化强国、实现中华民族伟大复兴的高度来对待。我们党立志于中华民族千秋伟业，必须培养一代又一代拥护中国共产党领导和我国社会主义制度、立志为中国特色社会主义事业奋斗终身的有用人才。",
    "办好思政课，最根本的是要全面贯彻党的教育方针，解决好培养什么人、怎样培养人、为谁培养人这个根本问题。要坚持马克思主义指导地位，贯彻新时代中国特色社会主义思想，坚持社会主义办学方向，落实立德树人的根本任务，努力培养担当民族复兴大任的时代新人，培养德智体美劳全面发展的社会主义建设者和接班人。",
    "今年是中华人民共和国成立70周年。坚持中国共产党领导，是中国人民的历史选择。70年来，中国共产党领导中国人民持续奋斗，各方面都取得了巨大成就。中国把自己的事情办好了，对世界而言就是贡献。",
    "要善于把党的领导和我国社会主义制度优势转化为国家治理效能，完善党委领导、政府负责、社会协同、公众参与、法治保障的社会治理体制，打造共建共治共享的社会治理格局。",
    "政法系统要在更高起点上，推动改革取得新的突破性进展，加快构建优化协同高效的政法机构职能体系。要全面落实司法责任制，让司法人员集中精力尽好责、办好案，提高司法质量、效率、公信力。",
    "向改革创新要动力，发挥引领高质量发展的重要动力源作用。要集聚和利用高端创新资源，积极开展重大科技项目研发合作，打造我国自主创新的重要源头和原始创新的主要策源地。",
    "中华民族正处在伟大复兴的关键时期，我们的改革发展正处在克难攻坚、闯关夺隘的重要阶段，迫切需要锐意进取、奋发有为、关键时顶得住的干部。",
    "要深化对国际国内金融形势的认识，正确把握金融本质，深化金融供给侧结构性改革，平衡好稳增长和防风险的关系，精准有效处置重点领域风险，深化金融改革开放，增强金融服务实体经济能力，坚决打好防范化解包括金融风险在内的重大风险攻坚战，推动我国金融业健康发展。",
    "经济社会是一个动态循环系统，不能长时间停摆。在确保疫情防控到位的前提下，推动非疫情防控重点地区企事业单位复工复产，恢复生产生活秩序，关系到为疫情防控提供有力物质保障，关系到民生保障和社会稳定，关系到实现全年经济社会发展目标任务。",
    "疫情对产业发展既是挑战也是机遇。一些传统行业受冲击较大，而智能制造、无人配送、在线消费、医疗健康等新兴产业展现出强大成长潜力。要以此为契机，改造提升传统产业，培育壮大新兴产业。",
    "港口是基础性、枢纽性设施，是经济发展的重要支撑。宁波舟山港在共建'一带一路'、长江经济带发展、长三角一体化发展等国家战略中具有重要地位，是'硬核'力量。要坚持一流标准，把港口建设好、管理好，努力打造世界一流强港，为国家发展作出更大贡献。",
    "民营企业、中小企业在我国发展特别是产业发展中具有重要地位。党中央特别考虑到了中小企业，出台一系列措施支持和帮助中小企业渡过难关。广大中小企业要发扬企业家精神，顽强拼搏，攻坚克难，努力战胜疫情挑战。",
    "当前我国疫情防控阶段性成效进一步巩固，复工复产取得重要进展，经济社会运行秩序加快恢复。同时，国际疫情持续蔓延，世界经济下行风险加剧，不稳定不确定因素显著增多。要坚持在常态化疫情防控中加快推进生产生活秩序全面恢复，力争把疫情造成的损失降到最低限度。",
    "绿水青山就是金山银山。保护生态环境就是保护生产力，改善生态环境就是发展生产力。要坚持节约资源和保护环境的基本国策，坚持节约优先、保护优先、自然恢复为主的方针，形成节约资源和保护环境的空间格局、产业结构、生产方式、生活方式，为人民创造良好生产生活环境。",
    "我们既要绿水青山，也要金山银山。宁要绿水青山，不要金山银山，而且绿水青山就是金山银山。我们绝不能以牺牲生态环境为代价换取经济的一时发展。",
    "生态兴则文明兴，生态衰则文明衰。生态环境是人类生存和发展的根基，生态环境变化直接影响文明兴衰演替。",
    "保护生态环境必须依靠制度、依靠法治。只有实行最严格的制度、最严密的法治，才能为生态文明建设提供可靠保障。",
    "青年兴则国家兴，青年强则国家强。青年一代有理想、有本领、有担当，国家就有前途，民族就有希望。中国梦是历史的、现实的，也是未来的；是我们这一代的，更是青年一代的。中华民族伟大复兴的中国梦终将在一代代青年的接力奋斗中变为现实。",
    "广大青年要坚定理想信念，志存高远，脚踏实地，勇做时代的弄潮儿，在实现中国梦的生动实践中放飞青春梦想，在为人民利益的不懈奋斗中书写人生华章！",
    "新时代中国青年处在中华民族发展的最好时期，既面临着难得的建功立业的人生际遇，也面临着'天将降大任于斯人'的时代使命。新时代中国青年要继续发扬五四精神，以实现中华民族伟大复兴为己任，不辜负党的期望、人民期待、民族重托，不辜负我们这个伟大时代。",
    "新时代中国青年要树立远大理想。青年的理想信念关乎国家未来。青年理想远大、信念坚定，是一个国家、一个民族无坚不摧的前进动力。",
    "新时代中国青年要热爱伟大祖国。对每一个中国人来说，爱国是本分，也是职责，是心之所系、情之所归。对新时代中国青年来说，热爱祖国是立身之本、成才之基。",
    "新时代中国青年要担当时代责任。时代呼唤担当，民族振兴是青年的责任。只要青年都勇挑重担、勇克难关、勇斗风险，中国特色社会主义就能充满活力、充满后劲、充满希望。",
    "新时代中国青年要勇于砥砺奋斗。奋斗是青春最亮丽的底色。民族复兴的使命要靠奋斗来实现，人生理想的风帆要靠奋斗来扬起。",
    "新时代中国青年要练就过硬本领。青年是苦练本领、增长才干的黄金时期。'青春虚度无所成，白首衔悲亦何及。'当今时代，知识更新不断加快，社会分工日益细化，新技术新模式新业态层出不穷。这既为青年施展才华、竞展风采提供了广阔舞台，也对青年能力素质提出了新的更高要求。",
    "新时代中国青年要锤炼品德修为。人无德不立，品德是为人之本。止于至善，是中华民族始终不变的人格追求。我们要建设的社会主义现代化强国，不仅要在物质上强，更要在精神上强。",
    "脱贫摘帽不是终点，而是新生活、新奋斗的起点。要切实做好巩固拓展脱贫攻坚成果同乡村振兴有效衔接各项工作，让脱贫基础更加稳固、成效更可持续。",
    "全面实施乡村振兴战略的深度、广度、难度都不亚于脱贫攻坚，必须加强顶层设计，以更有力的举措、汇聚更强大的力量来推进。",
    "民族团结是各族人民的生命线，是新疆发展进步的根本基石。要全面贯彻党的民族政策，高举各民族大团结旗帜，促进各民族像石榴籽一样紧紧抱在一起。",
    "文化是一个国家、一个民族的灵魂。文化兴国运兴，文化强民族强。没有高度的文化自信，没有文化的繁荣兴盛，就没有中华民族伟大复兴。",
    "坚定文化自信，推动社会主义文化繁荣兴盛。要坚持中国特色社会主义文化发展道路，激发全民族文化创新创造活力，建设社会主义文化强国。",
    "中国特色社会主义文化，源自于中华民族五千多年文明历史所孕育的中华优秀传统文化，熔铸于党领导人民在革命、建设、改革中创造的革命文化和社会主义先进文化，植根于中国特色社会主义伟大实践。",
    "要坚持把社会效益放在首位、社会效益和经济效益相统一，深化文化体制改革，完善文化产业规划和政策，加强文化市场体系建设，培育新型文化业态和文化消费模式，以高质量文化供给增强人们的文化获得感、幸福感。",
    "中华优秀传统文化是中华民族的精神命脉，是涵养社会主义核心价值观的重要源泉，也是我们在世界文化激荡中站稳脚跟的坚实根基。",
    "我们要坚持道路自信、理论自信、制度自信，最根本的还有一个文化自信。文化自信是更基本、更深沉、更持久的力量。",
  ],
  "zh-tw": [
    "人民對美好生活的嚮往，就是我們的奮鬥目標。人世間的一切幸福都需要靠辛勤的勞動來創造。我們的責任，就是要團結帶領全黨全國各族人民，繼續解放思想，堅持改革開放，不斷解放和發展社會生產力，努力解決群眾的生產生活困難，堅定不移走共同富裕的道路。",
    "我們的責任，就是要團結帶領全黨全國各族人民，接過歷史的接力棒，繼續為實現中華民族偉大復興而努力奮鬥。",
    "面對浩浩蕩蕩的時代潮流，面對人民群眾過上更好生活的殷切期待，我們不能有絲毫自滿，不能有絲毫懈怠，必須再接再厲、一往無前，繼續把中國特色社會主義事業推向前進，繼續為實現中華民族偉大復興的中國夢而努力奮鬥。",
    "我們正在從事的事業是偉大的，堅忍不拔才能勝利，半途而廢必將一事無成。",
    "我們的藍圖是宏偉的，我們的奮鬥必將是艱鉅的。全黨全國各族人民要團結一心，集思廣益用好機遇，眾志成城應對挑戰，立行立改破解難題，奮發有為進行創新，讓國家發展和人民生活一年比一年好。",
    "現在，大家都在討論中國夢，我以為，實現中華民族偉大復興，就是中華民族近代以來最偉大的夢想。這個夢想，凝聚了幾代中國人的夙願，體現了中華民族和中國人民的整體利益，是每一箇中華兒女的共同期盼。",
    "空談誤國，實幹興邦。我們這一代共產黨人一定要承前啟後、繼往開來，把我們的黨建設好，團結全體中華兒女把我們國家建設好，把我們民族發展好，繼續朝著中華民族偉大復興的目標奮勇前進。",
    "歷史告訴我們，每個人的前途命運都與國家和民族的前途命運緊密相連。國家好，民族好，大家才會好。實現中華民族偉大復興是一項光榮而艱鉅的事業，需要一代又一代中國人共同為之努力。",
    "檢驗我們一切工作的成效，最終都要看人民是否真正得到了實惠，人民生活是否真正得到了改善，這是堅持立黨為公、執政為民的本質要求，是黨和人民事業不斷髮展的重要保證。",
    "崇高信仰始終是我們黨的強大精神支柱，人民群眾始終是我們黨的堅實執政基礎。只要我們永不動搖信仰、永不脫離群眾，我們就能無往而不勝。",
    "我們的黨是全心全意為人民服務的政黨。黨領導人民已經取得舉世矚目的成就，我們完全有理由因此而自豪，但我們自豪而不自滿，決不會躺在過去的功勞簿上。",
    "打鐵還需自身硬。我們的責任，就是同全黨同志一道，堅持黨要管黨、從嚴治黨，切實解決自身存在的突出問題，切實改進工作作風，密切聯繫群眾，使我們黨始終成為中國特色社會主義事業的堅強領導核心。",
    "人民群眾是我們力量的源泉。我們深深知道，每個人的力量是有限的，但只要我們萬眾一心、眾志成城，就沒有克服不了的困難；每個人的工作時間是有限的，但全心全意為人民服務是無限的。",
    "責任重於泰山，事業任重道遠。我們一定要始終與人民心心相印、與人民同甘共苦、與人民團結奮鬥，夙夜在公，勤勉工作，努力向歷史、向人民交出一份合格的答卷。",
    "堅定理想信念，堅守共產黨人精神追求，始終是共產黨人安身立命的根本。對馬克思主義的信仰，對社會主義和共產主義的信念，是共產黨人的政治靈魂，是共產黨人經受住任何考驗的精神支柱。",
    "形象地說，理想信念就是共產黨人精神上的'鈣'，沒有理想信念，理想信念不堅定，精神上就會'缺鈣'，就會得'軟骨病'。",
    "物必先腐，而後蟲生。近年來，一些國家因長期積累的矛盾導致民怨載道、社會動盪、政權垮臺，其中貪汙腐敗就是一個很重要的原因。大量事實告訴我們，腐敗問題越演越烈，最終必然會亡黨亡國！我們要警醒啊！",
    "要堅持黨的群眾路線，堅持人民主體地位，時刻把群眾安危冷暖放在心上，及時準確瞭解群眾所思、所盼、所憂、所急，把群眾工作做實、做深、做細、做透。",
    "我們要與人民心心相印、與人民同甘共苦、與人民團結奮鬥。現在我們談不上說一塊苦，但一定要一塊過、一塊幹，保持和發揚黨的光榮傳統和優良作風，保持同人民群眾的血肉聯繫，切實把工作做好。",
    "規定就是規定，不加'試行'兩字，就是要表明一個堅決的態度，表明這個規定是剛性的。我們說了不是白說，說了就必須做到，把文件上寫的內容一一落到實處。",
    "對各類困難群眾，我們要格外關注、格外關愛、格外關心，時刻把他們的安危冷暖放在心上，關心他們的疾苦，千方百計幫助他們排憂解難。",
    "鄭板橋有一首詩寫道：'衙齋臥聽蕭蕭竹，疑是民間疾苦聲。些小吾曹州縣吏，一枝一葉總關情。'我們共產黨人對人民群眾的疾苦更要有這樣的情懷，要有仁愛之心、關愛之心，更多關注困難群眾，不斷提高全體人民生活水平。",
    "多想想我們乾的事情是不是黨和人民需要我們乾的？要一心一意為老百姓做事，心裡裝著困難群眾，多做雪中送炭的工作，常去貧困地區走一走，常到貧困戶家裡坐一坐，常同困難群眾聊一聊，多瞭解困難群眾的期盼，多解決困難群眾的問題，滿懷熱情為困難群眾辦事。",
    "領導不是百事通，不是萬能的。要做群眾的先生，先做群眾的學生。領導幹部要放下架子，甘當小學生，多同群眾交朋友，多向群眾請教。要真正悟透群眾是真正的英雄。",
    "大量事實證明，一個地方的工作，成在幹部作風，敗也在幹部作風；一個地方的事業，興在幹部作風，衰也在幹部作風。",
    "下去調研，要去一些困難多的地方、問題多的地方，調研不是光看好的。看了困難多、問題多的地方，才能幫助他們解決問題，也有利於我們正確決策。",
    "領導幹部是人民的公僕，必須始終牢記宗旨、牢記責任，自覺把權力行使的過程作為為人民服務的過程，自覺接受人民監督，做到為民用權、公正用權、依法用權、廉潔用權。",
    "實幹興邦，空談誤國。這個道理，我們都要牢記在心。各級領導幹部要堅持為民務實清廉，切實轉變工作作風，做到講實話、幹實事，敢作為、勇擔當，言必信、行必果。",
    "政貴有恆。為官一方，為政一時，既要大膽開展工作、銳意進取，又要保持大局穩定和工作連續性。真正做到一張好的藍圖一干到底，不折騰，不反覆，切實幹出成效來。",
    "改革開放是決定當代中國命運的關鍵一招，也是決定實現'兩個一百年'奮鬥目標、實現中華民族偉大復興的關鍵一招。",
    "我國改革已經進入攻堅期和深水區，我們必須以更大的政治勇氣和智慧，不失時機深化重要領域改革。改革開放中的矛盾只能用改革開放的辦法來解決。",
    "我國改革已經進入攻堅期和深水區，進一步深化改革，必須堅定信心、凝聚共識、統籌謀劃、協同推進。改革開放也是無止境的。停頓和倒退沒有出路。",
    "唯改革者進，唯創新者強，唯改革創新者勝。",
    "推出一批能叫得響、立得住、群眾認可的硬招實招，處理好改革'最先一公里'和'最後一公里'的關係，突破'中梗阻'，防止不作為，把改革方案的含金量充分展示出來，讓人民群眾有更多獲得感。",
    "改革開放是前無古人的嶄新事業，必須堅持正確的方法論，在不斷實踐探索中推進。摸著石頭過河，是富有中國特色、符合中國國情的改革方法。",
    "改革要抓鐵有痕、踏石留印，不能搞改革'弄虛作假'，要增強改革的系統性、整體性、協同性。",
    "改革遵循漸進性規律，要穩紮穩打、步步為先，既要敢於突破，又要一步一個腳印、穩紮穩打向前走，確保實現改革的目標任務。",
    "對改革進程中已經出現和可能出現的問題，困難要一個一個克服，問題要一個一個解決，既敢於出招又善於應招，做到蹄疾步穩、砥礪前行。",
    "改革開放只有進行時、沒有完成時。沒有改革開放，就沒有中國的今天，也就沒有中國的明天。",
    "人生在勤，勤則不匱。幸福不會從天降，美好生活靠勞動創造。全面建成小康社會的奮鬥目標，為廣大勞動群眾指明瞭光明的未來。",
    "志之所趨，無遠弗屆，窮山距海，不能限也。對想做愛做的事要敢試敢為，努力從無到有、從小到大，把理想變為現實。要敢於做先鋒，而不做過客、當看客，讓創新成為青春遠航的動力，讓創業成為青春搏擊的能量。",
    "為有犧牲多壯志，敢教日月換新天。要奮鬥就會有犧牲，我們要始終發揚大無畏精神和無私奉獻精神。奮鬥者是精神最為富足的人，也是最懂得幸福、最享受幸福的人。",
    "面對複雜變化的世界，人類社會向何處去？亞洲前途在哪裡？我認為，回答這些時代之問，我們要不畏浮雲遮望眼，善於撥雲見日，把握歷史規律，認清世界大勢。",
    "寶劍鋒從磨礪出，梅花香自苦寒來。人類的美好理想，都不可能唾手可得，都離不開篳路藍縷、手胼足胝的艱苦奮鬥。我們的國家，我們的民族，從積貧積弱一步一步走到今天的發展繁榮，靠的就是一代又一代人的頑強拼搏，靠的就是中華民族自強不息的奮鬥精神。",
    "實現我們的發展目標，實現中國夢，必須增強道路自信、理論自信、制度自信，千磨萬擊還堅勁，任爾東南西北風。",
    "功崇惟志，業廣惟勤。我國仍處於並將長期處於社會主義初級階段，實現中國夢，創造全體人民更加美好的生活，任重而道遠，需要我們每一個人繼續付出辛勤勞動和艱苦努力。",
    "積土而為山，積水而為海。幸福和美好未來不會自己出現，成功屬於勇毅而篤行的人。",
    "芳林新葉催陳葉，流水前波讓後波。改革開放40年來，我們以敢闖敢幹的勇氣和自我革新的擔當，闖出了一條新路、好路，實現了從'趕上時代'到'引領時代'的偉大跨越。",
    "建立中國共產黨、成立中華人民共和國、推進改革開放和中國特色社會主義事業，是五四運動以來我國發生的三大歷史性事件，是近代以來實現中華民族偉大復興的三大里程碑。",
    "我國社會大局保持長期穩定，成為世界上最有安全感的國家之一。忍飢挨餓、缺吃少穿、生活困頓這些幾千年來困擾我國人民的問題總體上一去不復返了！",
    "40年來取得的成就不是天上掉下來的，更不是別人恩賜施捨的，而是全黨全國各族人民用勤勞、智慧、勇氣幹出來的！我們用幾十年時間走完了發達國家幾百年走過的工業化歷程。在中國人民手中，不可能成為了可能。",
    "改革開放40年來，我們黨全部理論和實踐的主題是堅持和發展中國特色社會主義。在中國這樣一個有著5000多年文明史、13億多人口的大國推進改革發展，沒有可以奉為金科玉律的教科書，也沒有可以對中國人民頤指氣使的教師爺。",
    "改什麼、怎麼改必須以是否符合完善和發展中國特色社會主義制度、推進國家治理體系和治理能力現代化的總目標為根本尺度，該改的、能改的我們堅決改，不該改的、不能改的堅決不改。",
    "實現祖國完全統一，是全體中華兒女共同心願，是中華民族根本利益所在。我們有堅定的政治決心和強大能力維護國家主權和領土完整，祖國的神聖領土一寸都不能分裂出去！",
    "事者，生於慮，成於務，失於傲。偉大夢想不是等得來、喊得來的，而是拼出來、幹出來的。我們現在所處的，是一個船到中流浪更急、人到半山路更陡的時候，是一個愈進愈難、愈進愈險而又不進則退、非進不可的時候。",
    "信仰、信念、信心，任何時候都至關重要。小到一個人、一個集體，大到一個政黨、一個民族、一個國家，只要有信仰、信念、信心，就會愈挫愈奮、愈戰愈勇，否則就會不戰自敗、不打自垮。",
    "在近代以來漫長的歷史進程中，中國人民經歷了太多太多的磨難，付出了太多太多的犧牲，進行了太多太多的拼搏。現在，中國人民和中華民族在歷史進程中積累的強大能量已經充分爆發出來了，為實現中華民族偉大復興提供了勢不可擋的磅礴力量。",
    "建成社會主義現代化強國，實現中華民族偉大復興，是一場接力跑，我們要一棒接著一棒跑下去，每一代人都要為下一代人跑出一個好成績。",
    "中國特色社會主義不是從天上掉下來的，而是在改革開放40年的偉大實踐中得來的，是在中華人民共和國成立近70年的持續探索中得來的，是在我們黨領導人民進行偉大社會革命97年的實踐中得來的，是黨和人民歷經千辛萬苦、付出各種代價取得的寶貴成果。",
    "新時代堅持和發展中國特色社會主義，需要大批能把馬克思主義中國化講好的人才，講人民群眾聽得懂、聽得進的話語，讓黨的創新理論'飛入尋常百姓家'。",
    "不忘初心、牢記使命，必須發揚鬥爭精神，勇於擔當作為。我們黨誕生於國家內憂外患、民族危難之時，一出生就銘刻著鬥爭的烙印，一路走來就是在鬥爭中求得生存、獲得發展、贏得勝利。",
    "我們講的鬥爭，不是為了鬥爭而鬥爭，也不是為了一己私利而鬥爭，而是為了實現人民對美好生活的嚮往、實現中華民族偉大復興知重負重、苦幹實幹、攻堅克難。",
    "衡量黨員、幹部有沒有鬥爭精神、是不是敢於擔當，就要看面對大是大非敢不敢亮劍、面對矛盾敢不敢迎難而上、面對危機敢不敢挺身而出、面對失誤敢不敢承擔責任、面對歪風邪氣敢不敢堅決鬥爭。",
    "心有所信，方能行遠。面向未來，走好新時代的長征路，我們更需要堅定理想信念、矢志拼搏奮鬥。",
    "實踐告訴我們，偉大事業都始於夢想。夢想是激發活力的源泉。在建成社會主義現代化強國、實現中華民族偉大復興的征途上，每一個行業、每一個人都要心懷夢想、奮勇拼搏，一步一個腳印，一棒接著一棒，在奮力奔跑和接續奮鬥中成就夢想。",
    "世界上最大的幸福莫過於為人民幸福而奮鬥。心中裝著百姓，手中握有真理，腳踏人間正道，我們信心十足、力量十足。",
    "中國夢是兩岸同胞共同的夢，民族復興、國家強盛，兩岸中國人才能過上富足美好的生活。在中華民族走向偉大復興的進程中，臺灣同胞定然不會缺席。",
    "愛國主義是中華民族的民族心、民族魂。我們要把學習的具體目標同民族復興的宏大目標結合起來，為之而奮鬥。只有把小我融入大我，才會有海一樣的胸懷，山一樣的崇高。",
    "我們推動媒體融合發展，是要做大做強主流輿論，鞏固全黨全國人民團結奮鬥的共同思想基礎，為實現'兩個一百年'奮鬥目標、實現中華民族偉大復興的中國夢提供強大精神力量和輿論支持。",
    "我們在扶貧脫貧方面取得的成就和經驗，為全球減貧事業貢獻了中國智慧和中國方案，彰顯了中國共產黨領導和我國社會主義制度的政治優勢。在發展中國家中，只有中國實現了快速發展和大規模減貧同步，這是一個了不起的人間奇蹟。",
    "今天，在中國共產黨領導下，我們開闢了中國特色社會主義道路，形成了中國特色社會主義理論體系，建立了中國特色社會主義制度，發展了中國特色社會主義文化，推動中國特色社會主義進入了新時代。中國人民擁有了前所未有的道路自信、理論自信、制度自信、文化自信，中華民族偉大復興展現出前所未有的光明前景！",
    "中國特色社會主義進入新時代，我們比歷史上任何時期都更接近、更有信心和能力實現中華民族偉大復興。我們千萬不能在一片喝彩聲、讚揚聲中喪失革命精神和鬥志，逐漸陷入安於現狀、不思進取、貪圖享樂的狀態，而是要牢記船到中流浪更急、人到半山路更陡。",
    "要引導人們樹立正確的歷史觀、國家觀、民族觀、文化觀，不斷鞏固各族人民對偉大祖國的認同、對中華民族的認同、對中國特色社會主義道路的認同。",
    "我們既要堅信中國的發展前途光明，又要充分認識到道路曲折、困難很多，發揮中國共產黨領導和我國社會主義制度的政治優勢，集中力量辦大事，打好防範和抵禦風險的有準備之戰，打好化險為夷、轉危為機的戰略主動戰。",
    "要充分發揮集中力量辦大事的制度優勢和超大規模的市場優勢，打好產業基礎高級化、產業鏈現代化的攻堅戰。",
    "馬克思主義產生和發展、社會主義國家誕生和發展的歷程充滿著鬥爭的艱辛。建立中國共產黨、成立中華人民共和國、實行改革開放、推進新時代中國特色社會主義事業，都是在鬥爭中誕生、在鬥爭中發展、在鬥爭中壯大的。",
    "當今世界正處於百年未有之大變局，我們黨領導的偉大斗爭、偉大工程、偉大事業、偉大夢想正在如火如荼進行，勝利實現我們黨確定的目標任務，必須發揚鬥爭精神，增強鬥爭本領。",
    "新時代中國特色社會主義是我們黨領導人民進行偉大社會革命的成果，也是我們黨領導人民進行偉大社會革命的繼續，必須一以貫之進行下去。一場社會革命要取得最終勝利，往往需要一個漫長的歷史過程。",
    "我國疫情防控和復工復產之所以能夠有力推進，根本原因是黨的領導和我國社會主義制度的優勢發揮了無可比擬的重要作用。發展環境越是嚴峻複雜，越要堅定不移深化改革，健全各方面制度，完善治理體系，善於運用制度優勢應對風險挑戰衝擊。",
    "我們黨之所以能夠完成近代以來各種政治力量不可能完成的艱鉅任務，帶領人民取得革命、建設、改革的輝煌成就，就在於始終把馬克思主義作為行動指南，始終堅持用馬克思主義中國化最新成果武裝全黨，使全黨始終保持統一的思想、堅定的意志、協調的行動、強大的戰鬥力。",
    "要注重提高馬克思主義理論水平，學深悟透，融會貫通，掌握辯證唯物主義和歷史唯物主義，掌握貫穿其中的馬克思主義立場觀點方法，掌握中國化的馬克思主義，做馬克思主義的堅定信仰者、忠實實踐者。",
    "思政課要解決學生理想信念問題。要讓有信仰的人講信仰。對馬克思主義的信仰，對社會主義和共產主義的信念，只有首先在思政課教師心中紮下根，才能在學生心中開花結果。",
    "要教育引導學生多讀讀馬克思主義經典著作、當代中國馬克思主義理論著作、中華優秀傳統文化典籍等。要開出書單、指出重點，讓學生正確理解經典著作，掌握馬克思主義精髓，感知中華文化魅力。",
    "繩短不能汲深井，淺水難以負大舟。對領導幹部來說，把握全局、謀劃發展的戰略能力是十分重要的。形成和提升這方面的能力，就要全面掌握辯證唯物主義和歷史唯物主義的世界觀和方法論。",
    "要把課堂教學和實踐教學有機結合起來，充分運用豐富的歷史文化資源，緊密聯繫中國共產黨和中國人民的奮鬥歷程，深刻領悟馬克思主義中國化的內在道理，深刻領悟為什麼歷史和人民選擇了中國共產黨和社會主義，進一步堅定'四個自信'。",
    "疫情發生以來，包括軍隊在內的廣大醫務工作者發揚特別能吃苦、特別能戰鬥的精神，義無反顧奔赴湖北和武漢，毫無畏懼投入防控救治工作，同時間賽跑，與病魔較量，你們真正做到了救死扶傷、大愛無疆。你們是光明的使者、希望的使者，是最美的天使，是真正的英雄！黨和人民感謝你們！",
    "在中國共產黨的堅強領導下，充分發揮中國特色社會主義制度優勢，緊緊依靠人民群眾，堅定信心、同舟共濟、科學防治、精準施策，我們完全有信心、有能力打贏這場疫情防控阻擊戰。",
    "確保人民群眾生命安全和身體健康，是我們黨治國理政的一項重大任務。這次抗擊新冠肺炎疫情，是對國家治理體系和治理能力的一次大考。",
    "我們要在全社會大力弘揚偉大抗疫精神，使之轉化為全面建設社會主義現代化國家、實現中華民族偉大復興的強大力量。",
    "歷史和現實都告訴我們，只要不斷解放和發展社會生產力，不斷增強經濟實力、科技實力、綜合國力，不斷讓廣大人民的獲得感、幸福感、安全感日益充實起來，不斷讓堅持和發展中國特色社會主義、實現中華民族偉大復興的物質基礎日益堅實起來，我們就一定能夠使中國特色社會主義航船乘風破浪、行穩致遠。",
    "中國人民抗日戰爭勝利75年來，中國發生了翻天覆地的變化。中國共產黨團結帶領全國各族人民發憤圖強、艱苦創業，創造了舉世矚目的發展成就，成功開闢了中國特色社會主義道路，中國特色社會主義進入新時代，脫貧攻堅戰、全面建成小康社會勝利在望，中華民族偉大復興迎來了光明前景。",
    "中國人民在抗日戰爭的壯闊進程中孕育出偉大抗戰精神，向世界展示了天下興亡、匹夫有責的愛國情懷，視死如歸、寧死不屈的民族氣節，不畏強暴、血戰到底的英雄氣概，百折不撓、堅忍不拔的必勝信念。偉大抗戰精神，是中國人民彌足珍貴的精神財富，將永遠激勵中國人民克服一切艱難險阻、為實現中華民族偉大復興而奮鬥。",
    "你們今天是小樹苗，將來要長成參天大樹，中華民族偉大復興的中國夢將在你們身上實現。希望同學們把紅色基因傳承好，好好學習知識和本領，努力成長為德智體美勞全面發展的社會主義建設者和接班人。",
    "黨的十八大以來，我們著眼於實現中華民族偉大復興中國夢，圍繞實現黨在新時代的強軍目標，提出一系列重大方針原則，作出一系列重大決策部署，推進一系列重大工作，開創了強軍事業新局面。",
    "推動我國汽車製造業高質量發展，必須加強關鍵核心技術和關鍵零部件的自主研發，實現技術自立自強，做強做大民族品牌。當今世界製造業競爭激烈，要搶抓機遇，大力發展戰略性新興產業，實現彎道超車。",
    "新時代堅持和發展中國特色社會主義，要全面貫徹新發展理念，堅持統籌推進'五位一體'總體佈局、協調推進'四個全面'戰略佈局，加強頂層設計和戰略佈局，增強發展的整體性、協同性。",
    "面對新形勢新任務，必須全面貫徹新時代黨的治藏方略，鑄牢中華民族共同體意識，提升發展質量，保障和改善民生，推進生態文明建設，加強黨的組織和政權建設，確保國家安全和長治久安。",
    "新形勢需要新擔當、呼喚新作為。新時代經濟特區建設要高舉中國特色社會主義偉大旗幟，從我國進入新發展階段大局出發，落實新發展理念，緊扣推動高質量發展、構建新發展格局，以一往無前的奮鬥姿態、風雨無阻的精神狀態，改革不停頓，開放不止步，在更高起點上推進改革開放。",
    "銘記偉大勝利，推進偉大事業，必須堅持推進經濟社會發展，不斷壯大我國綜合國力。落後就要捱打，發展才能自強。只要我們統籌推進'五位一體'總體佈局、協調推進'四個全面'戰略佈局，堅定不移貫徹新發展理念，構建新發展格局，就一定能夠實現更高質量、更有效率、更加公平、更可持續、更為安全的發展，不斷創造讓世界驚歎的更大奇蹟！",
    "黨的十八大以來，我們黨關於生態文明建設的思想不斷豐富和完善。在'五位一體'總體佈局中生態文明建設是其中一位，在新時代堅持和發展中國特色社會主義基本方略中堅持人與自然和諧共生是其中一條基本方略，在新發展理念中綠色是其中一大理念，在三大攻堅戰中汙染防治是其中一大攻堅戰。",
    "實施擴大內需戰略，是當前應對疫情衝擊的需要，是保持我國經濟長期持續健康發展的需要，也是滿足人民日益增長的美好生活的需要。",
    "消費是我國經濟增長的重要引擎，中等收入群體是消費的重要基礎。目前，我國約有4億中等收入人口，絕對規模世界最大。要把擴大中等收入群體規模作為重要政策目標，使更多普通勞動者通過自身努力進入中等收入群體。",
    "製造業是國家經濟命脈所繫。國有大型企業要發揮主力軍作用，在抓好常態化疫情防控的前提下，帶動上下游產業和中小企業全面復工復產。",
    "長期以來，山西興於煤、困於煤，一煤獨大導致產業單一。建設轉型綜合改革示範區，是黨中央賦予山西的一項重大任務。山西要有緊迫感，更要有長遠戰略謀劃，正確的就要堅持下去，久久為功，不要反覆、不要折騰，爭取早日蹚出一條轉型發展的新路子。",
    "要更加及時有效解決企業恢復生產經營面臨的各種困難和問題，把擴大內需各項政策舉措抓實，把實體經濟特別是製造業做強做優，持續推動產業結構調整優化，大力加強科技創新，在新基建、新技術、新材料、新裝備、新產品、新業態上不斷取得突破。",
    "我們要堅持一箇中國原則和'九二共識'，鞏固和發展兩岸關係和平發展的基礎，深化兩岸經濟文化交流合作，造福兩岸同胞。臺灣問題因民族弱亂而產生，必將隨著民族復興而終結！",
    "當前形勢下，辦好思政課，要從堅持和發展中國特色社會主義、建設社會主義現代化強國、實現中華民族偉大復興的高度來對待。我們黨立志於中華民族千秋偉業，必須培養一代又一代擁護中國共產黨領導和我國社會主義制度、立志為中國特色社會主義事業奮鬥終身的有用人才。",
    "辦好思政課，最根本的是要全面貫徹黨的教育方針，解決好培養什麼人、怎樣培養人、為誰培養人這個根本問題。要堅持馬克思主義指導地位，貫徹新時代中國特色社會主義思想，堅持社會主義辦學方向，落實立德樹人的根本任務，努力培養擔當民族復興大任的時代新人，培養德智體美勞全面發展的社會主義建設者和接班人。",
    "今年是中華人民共和國成立70週年。堅持中國共產黨領導，是中國人民的歷史選擇。70年來，中國共產黨領導中國人民持續奮鬥，各方面都取得了巨大成就。中國把自己的事情辦好了，對世界而言就是貢獻。",
    "要善於把黨的領導和我國社會主義制度優勢轉化為國家治理效能，完善黨委領導、政府負責、社會協同、公眾參與、法治保障的社會治理體制，打造共建共治共享的社會治理格局。",
    "政法系統要在更高起點上，推動改革取得新的突破性進展，加快構建優化協同高效的政法機構職能體系。要全面落實司法責任制，讓司法人員集中精力盡好責、辦好案，提高司法質量、效率、公信力。",
    "向改革創新要動力，發揮引領高質量發展的重要動力源作用。要集聚和利用高端創新資源，積極開展重大科技項目研發合作，打造我國自主創新的重要源頭和原始創新的主要策源地。",
    "中華民族正處在偉大復興的關鍵時期，我們的改革發展正處在克難攻堅、闖關奪隘的重要階段，迫切需要銳意進取、奮發有為、關鍵時頂得住的幹部。",
    "要深化對國際國內金融形勢的認識，正確把握金融本質，深化金融供給側結構性改革，平衡好穩增長和防風險的關係，精準有效處置重點領域風險，深化金融改革開放，增強金融服務實體經濟能力，堅決打好防範化解包括金融風險在內的重大風險攻堅戰，推動我國金融業健康發展。",
    "經濟社會是一個動態循環系統，不能長時間停擺。在確保疫情防控到位的前提下，推動非疫情防控重點地區企事業單位復工復產，恢復生產生活秩序，關係到為疫情防控提供有力物質保障，關係到民生保障和社會穩定，關係到實現全年經濟社會發展目標任務。",
    "疫情對產業發展既是挑戰也是機遇。一些傳統行業受衝擊較大，而智能製造、無人配送、在線消費、醫療健康等新興產業展現出強大成長潛力。要以此為契機，改造提升傳統產業，培育壯大新興產業。",
    "港口是基礎性、樞紐性設施，是經濟發展的重要支撐。寧波舟山港在共建'一帶一路'、長江經濟帶發展、長三角一體化發展等國家戰略中具有重要地位，是'硬核'力量。要堅持一流標準，把港口建設好、管理好，努力打造世界一流強港，為國家發展作出更大貢獻。",
    "民營企業、中小企業在我國發展特別是產業發展中具有重要地位。黨中央特別考慮到了中小企業，出臺一系列措施支持和幫助中小企業渡過難關。廣大中小企業要發揚企業家精神，頑強拼搏，攻堅克難，努力戰勝疫情挑戰。",
    "當前我國疫情防控階段性成效進一步鞏固，復工復產取得重要進展，經濟社會運行秩序加快恢復。同時，國際疫情持續蔓延，世界經濟下行風險加劇，不穩定不確定因素顯著增多。要堅持在常態化疫情防控中加快推進生產生活秩序全面恢復，力爭把疫情造成的損失降到最低限度。",
    "綠水青山就是金山銀山。保護生態環境就是保護生產力，改善生態環境就是發展生產力。要堅持節約資源和保護環境的基本國策，堅持節約優先、保護優先、自然恢復為主的方針，形成節約資源和保護環境的空間格局、產業結構、生產方式、生活方式，為人民創造良好生產生活環境。",
    "我們既要綠水青山，也要金山銀山。寧要綠水青山，不要金山銀山，而且綠水青山就是金山銀山。我們絕不能以犧牲生態環境為代價換取經濟的一時發展。",
    "生態興則文明興，生態衰則文明衰。生態環境是人類生存和發展的根基，生態環境變化直接影響文明興衰演替。",
    "保護生態環境必須依靠制度、依靠法治。只有實行最嚴格的制度、最嚴密的法治，才能為生態文明建設提供可靠保障。",
    "青年興則國家興，青年強則國家強。青年一代有理想、有本領、有擔當，國家就有前途，民族就有希望。中國夢是歷史的、現實的，也是未來的；是我們這一代的，更是青年一代的。中華民族偉大復興的中國夢終將在一代代青年的接力奮鬥中變為現實。",
    "廣大青年要堅定理想信念，志存高遠，腳踏實地，勇做時代的弄潮兒，在實現中國夢的生動實踐中放飛青春夢想，在為人民利益的不懈奮鬥中書寫人生華章！",
    "新時代中國青年處在中華民族發展的最好時期，既面臨著難得的建功立業的人生際遇，也面臨著'天將降大任於斯人'的時代使命。新時代中國青年要繼續發揚五四精神，以實現中華民族偉大復興為己任，不辜負黨的期望、人民期待、民族重託，不辜負我們這個偉大時代。",
    "新時代中國青年要樹立遠大理想。青年的理想信念關乎國家未來。青年理想遠大、信念堅定，是一個國家、一個民族無堅不摧的前進動力。",
    "新時代中國青年要熱愛偉大祖國。對每一箇中國人來說，愛國是本分，也是職責，是心之所繫、情之所歸。對新時代中國青年來說，熱愛祖國是立身之本、成才之基。",
    "新時代中國青年要擔當時代責任。時代呼喚擔當，民族振興是青年的責任。只要青年都勇挑重擔、勇克難關、勇鬥風險，中國特色社會主義就能充滿活力、充滿後勁、充滿希望。",
    "新時代中國青年要勇於砥礪奮鬥。奮鬥是青春最亮麗的底色。民族復興的使命要靠奮鬥來實現，人生理想的風帆要靠奮鬥來揚起。",
    "新時代中國青年要練就過硬本領。青年是苦練本領、增長才乾的黃金時期。'青春虛度無所成，白首銜悲亦何及。'當今時代，知識更新不斷加快，社會分工日益細化，新技術新模式新業態層出不窮。這既為青年施展才華、競展風采提供了廣闊舞臺，也對青年能力素質提出了新的更高要求。",
    "新時代中國青年要錘鍊品德修為。人無德不立，品德是為人之本。止於至善，是中華民族始終不變的人格追求。我們要建設的社會主義現代化強國，不僅要在物質上強，更要在精神上強。",
    "脫貧摘帽不是終點，而是新生活、新奮鬥的起點。要切實做好鞏固拓展脫貧攻堅成果同鄉村振興有效銜接各項工作，讓脫貧基礎更加穩固、成效更可持續。",
    "全面實施鄉村振興戰略的深度、廣度、難度都不亞於脫貧攻堅，必須加強頂層設計，以更有力的舉措、匯聚更強大的力量來推進。",
    "民族團結是各族人民的生命線，是新疆發展進步的根本基石。要全面貫徹黨的民族政策，高舉各民族大團結旗幟，促進各民族像石榴籽一樣緊緊抱在一起。",
    "文化是一個國家、一個民族的靈魂。文化興國運興，文化強民族強。沒有高度的文化自信，沒有文化的繁榮興盛，就沒有中華民族偉大復興。",
    "堅定文化自信，推動社會主義文化繁榮興盛。要堅持中國特色社會主義文化發展道路，激發全民族文化創新創造活力，建設社會主義文化強國。",
    "中國特色社會主義文化，源自於中華民族五千多年文明歷史所孕育的中華優秀傳統文化，熔鑄於黨領導人民在革命、建設、改革中創造的革命文化和社會主義先進文化，植根於中國特色社會主義偉大實踐。",
    "要堅持把社會效益放在首位、社會效益和經濟效益相統一，深化文化體制改革，完善文化產業規劃和政策，加強文化市場體系建設，培育新型文化業態和文化消費模式，以高質量文化供給增強人們的文化獲得感、幸福感。",
    "中華優秀傳統文化是中華民族的精神命脈，是涵養社會主義核心價值觀的重要源泉，也是我們在世界文化激盪中站穩腳跟的堅實根基。",
    "我們要堅持道路自信、理論自信、制度自信，最根本的還有一個文化自信。文化自信是更基本、更深沉、更持久的力量。",
  ],
  en: [
    "The people's yearning for a better life is our goal of struggle. All happiness in the world must be created through hard work. Our responsibility is to unite and lead the entire Party and people of all ethnic groups in the country, continue to emancipate the mind, persist in reform and opening up, continuously unleash and develop social productive forces, strive to solve the people's difficulties in production and daily life, and unswervingly pursue the path of common prosperity.",
    "Our responsibility is to unite and lead the entire Party and people of all ethnic groups in the country, take up the baton of history, and continue to strive for the great rejuvenation of the Chinese nation.",
    "Facing the mighty tide of the times and the earnest expectations of the people for a better life, we must not be the least bit complacent or slack off in the slightest. We must continue to make persistent efforts, press ahead courageously, continue to advance the cause of socialism with Chinese characteristics, and continue to strive for the Chinese Dream of the great rejuvenation of the Chinese nation.",
    "The cause we are engaged in is great. Only through perseverance can we achieve victory; giving up halfway will lead to accomplishing nothing.",
    "Our blueprint is grand, and our struggle will inevitably be arduous. The entire Party and people of all ethnic groups in the country must unite as one, pool wisdom to seize opportunities, unite like a fortress to tackle challenges, take prompt actions to solve difficult problems, and forge ahead with innovation, so that our country's development and people's lives get better year by year.",
    "Nowadays, everyone is discussing the Chinese Dream. In my view, realizing the great rejuvenation of the Chinese nation is the greatest dream of the Chinese nation in modern times. This dream embodies the long-cherished wishes of generations of Chinese, reflects the overall interests of the Chinese nation and the Chinese people, and is the common aspiration of every Chinese son and daughter.",
    "Empty talk harms the country, while solid work makes it prosper. We Communists of this generation must serve as a link between past and future, build our Party well, unite all Chinese sons and daughters to build our country well and develop our nation well, and continue to march courageously towards the goal of the great rejuvenation of the Chinese nation.",
    "History tells us that everyone's future and destiny are closely linked to the future and destiny of the country and the nation. Only when the country and the nation do well can everyone do well. Realizing the great rejuvenation of the Chinese nation is an honorable and arduous undertaking that requires the concerted efforts of generations of Chinese people.",
    "Ultimately, the effectiveness of all our work must be judged by whether the people have truly received tangible benefits and whether their lives have truly improved. This is the essential requirement of upholding the principle of building the Party for the public good and governing for the people, and an important guarantee for the continuous development of the Party and the people's cause.",
    "Lofty faith has always been the strong spiritual pillar of our Party, and the masses of the people have always been the solid foundation for our Party's governance. As long as we never waver in our faith and never detach ourselves from the people, we will be invincible.",
    "Our Party is a political party that serves the people wholeheartedly. The Party has led the people to achieve accomplishments that have captured the world's attention, and we have every reason to be proud of this. However, we are proud but not complacent, and we will never rest on our past laurels.",
    "To forge iron, one must be strong oneself. Our responsibility is to work together with all comrades in the Party to uphold the principle that the Party must govern the Party and govern it strictly, effectively solve our own prominent problems, genuinely improve our work style, maintain close ties with the masses, and ensure that our Party always remains the strong leading core of the cause of socialism with Chinese characteristics.",
    "The masses of the people are the source of our strength. We deeply understand that each individual's strength is limited, but as long as we unite our hearts and efforts, there is no difficulty we cannot overcome; each person's working time is limited, but serving the people wholeheartedly is limitless.",
    "Responsibility is weightier than Mount Tai, and the cause ahead is long and arduous. We must always maintain heart-to-heart connections with the people, share weal and woe with them, and strive together with them, devoting ourselves to public duties day and night through diligent work, striving to deliver a satisfactory answer to history and to the people.",
    "Strengthening ideals and convictions and upholding the spiritual pursuit of Communists have always been the foundation for Communists to settle down and get on with their pursuit. Faith in Marxism, and belief in socialism and communism are the political soul of Communists and the spiritual pillar that enables them to withstand any test.",
    "Figuratively speaking, ideals and convictions are the spiritual 'calcium' of Communists. Without ideals and convictions, or if they are not firm, one will suffer from a spiritual 'calcium deficiency' and develop 'weak bones'.",
    "Things must first rot before worms can breed. In recent years, accumulated long-term conflicts in some countries have led to widespread public discontent, social unrest, and the collapse of regimes, with corruption being a very important contributing factor. Numerous facts tell us that if corruption worsens unchecked, it will ultimately lead to the ruin of the Party and the nation! We must stay vigilant!",
    "We must adhere to the Party's mass line, uphold the principal position of the people, always keep the people's well-being and security in mind, promptly and accurately understand their thoughts, expectations, concerns, and urgent needs, and carry out mass work concretely, deeply, meticulously, and thoroughly.",
    "We must maintain heart-to-heart connections with the people, share weal and woe with them, and strive together with them. While we cannot say we are sharing the exact same hardships now, we must definitely go through these times together, work together, preserve and promote the Party's glorious traditions and fine work style, maintain flesh-and-blood ties with the masses, and earnestly do our work well.",
    "A regulation is a regulation; the absence of the word 'trial' signifies a resolute attitude, indicating that this regulation is rigid. What we say is not just empty words; what we say must be done, and what is written in the documents must be implemented point by point.",
    "We must pay extra attention, care, and concern to all types of people in difficulty, always keeping their well-being and security in mind, caring about their hardships, and doing everything possible to help them overcome their difficulties.",
    "Zheng Banqiao wrote a poem: 'Lying in the official residence, I hear the rustling bamboo, suspecting it is the sound of the people's suffering. Though we are but lowly county officials, every branch and leaf is linked to our concern.' We Communists must possess even greater compassion for the people's hardships, have a benevolent and caring heart, pay more attention to people in difficulty, and continuously improve the living standards of all the people.",
    "We should reflect more on whether what we do is needed by the Party and the people. We must wholeheartedly work for the people, keeping those in difficulty in our hearts, doing more work that provides timely help. We should frequently visit poor areas, sit in the homes of poor households, chat with people in difficulty, better understand their expectations, solve more of their problems, and serve them with enthusiasm.",
    "Leaders are not know-it-alls, nor are they omnipotent. To be teachers to the masses, one must first be their student. Leading officials must shed their airs, be willing to be primary school students, make friends with the masses more often, and seek advice from them. We must genuinely understand and grasp the truth that the masses are the real heroes.",
    "Numerous facts prove that in any locality, success in work comes down to the officials' work style, and failure also stems from it; the flourishing of a locality's cause depends on the officials' work style, and its decline is also due to it.",
    "When conducting field research, we must go to places with many difficulties and problems; research isn't just about looking at the good aspects. Only by seeing places with many difficulties and problems can we help them solve their problems, which is also beneficial for our correct decision-making.",
    "Leading officials are public servants of the people. They must always bear in mind the Party's purpose and their responsibilities, consciously view the process of exercising power as serving the people, consciously accept public oversight, and ensure power is exercised for the people, justly, according to law, and with integrity.",
    "Solid work prospers the nation, empty talk harms it. We must all keep this principle firmly in mind. Leading officials at all levels must persist in being down-to-earth, pragmatic, and clean, genuinely transform their work style, speak the truth, do practical work, dare to act and take responsibility, be true to their word, and be resolute in action.",
    "Good governance values constancy. When governing a locality or for a term of office, one must both boldly carry out work, forge ahead with determination, and maintain overall stability and work continuity. Truly ensure that one good blueprint is implemented to the end, without turmoil or reversals, achieving tangible results.",
    "Reform and opening up is the crucial move that determined the destiny of contemporary China, and it is also the crucial move for achieving the 'Two Centenary Goals' and the great rejuvenation of the Chinese nation.",
    "China's reform has entered a critical zone and deep-water area. We must, with greater political courage and wisdom, lose no time in deepening reforms in key sectors. Contradictions arising from reform and opening up can only be resolved through the methods of reform and opening up.",
    "China's reform has entered a critical zone and deep-water area. To further deepen reform, we must firm up confidence, build consensus, plan holistically, and advance in a coordinated manner. Reform and opening up is also never-ending. Halting or retreating offers no way out.",
    "Only reformers advance, only innovators are strong, only those who reform and innovate prevail.",
    "We must launch a batch of effective, enduring, and publicly recognized concrete and practical measures, properly handling the relationship between the 'first mile' and the 'last mile' of reform, breaking through 'middle obstructions', preventing inaction, fully demonstrating the substance of reform plans, and giving the people a greater sense of gain.",
    "Reform and opening up is an unprecedented new undertaking. We must adhere to correct methodologies and advance through continuous practical exploration. 'Crossing the river by feeling the stones' is a reform method rich in Chinese characteristics and suited to China's national conditions.",
    "Reform must be carried out with tangible, lasting force, like iron leaving a mark and stepping on stone leaving an imprint. We must not engage in reform 'falsification', but enhance its systemic, holistic, and synergistic nature.",
    "Reform follows the law of gradualism; we must proceed steadily and step-by-step. While daring to make breakthroughs, we must also move forward step-by-step and steadily to ensure the achievement of reform goals and tasks.",
    "Regarding problems that have already emerged or may emerge in the reform process, we must overcome difficulties one by one and solve problems one by one. We must be both bold in making moves and adept in responding, ensuring swift yet steady progress and forging ahead resolutely.",
    "Reform and opening up is always ongoing and will never be completed. Without it, there would be no China of today, nor the China of tomorrow.",
    "Life lies in diligence; diligence ensures no deprivation. Happiness does not fall from the sky; a good life is created through labor. The goal of comprehensively building a moderately prosperous society has illuminated a bright future for the broad working masses.",
    "Where ambition reaches, nothing is too far, not even mountains and seas can limit it. We must dare to attempt and act on what we aspire to do and love, striving to grow something from nothing, from small to large, turning ideals into reality. We must dare to be pioneers, not passers-by or spectators, making innovation the driving force for youth's voyage and entrepreneurship the energy for youth's struggle.",
    "Having lofty aspirations, we dare to sacrifice and change the world. Struggle entails sacrifice, and we must always promote the spirit of great fearlessness and selfless dedication. Those who struggle are the most spiritually enriched people, and the ones who best understand and enjoy happiness.",
    "Facing a complex and changing world, where is human society heading? What is the future of Asia? I believe that to answer these questions of our era, we must not let fleeting clouds obscure our vision, but be adept at seeing through to the truth, grasping historical laws, and discerning the global trend.",
    "A fine sword is honed from grinding, and plum blossom fragrance comes from bitter cold. Beautiful ideals of humanity can never be obtained easily; they all require arduous, pioneering struggles with calloused hands and feet. Our country and our nation have moved step-by-step from extreme poverty and weakness to today's development and prosperity, relying on the tenacious struggle of generation after generation and the Chinese nation's spirit of ceaseless self-improvement.",
    "To achieve our development goals and realize the Chinese Dream, we must strengthen confidence in our path, theory, system, and culture, remaining steadfast through countless trials and tribulations, regardless of the winds from any direction.",
    "Great achievement comes from high ambition, and extensive accomplishment from tireless diligence. China is still and will long remain in the primary stage of socialism. Realizing the Chinese Dream and creating a better life for all our people is a long and arduous task, requiring every one of us to continue working diligently and strenuously.",
    "Piling up earth makes a mountain, gathering water makes an ocean. Happiness and a bright future do not appear on their own; success belongs to those who are courageous, resolute, and persistent in action.",
    "New leaves push out old leaves in lush forests, and waves ahead give way to those behind in flowing water. Over the past 40 years of reform and opening up, with the courage to venture and experiment and a commitment to self-reinvention, we have blazed a new, good path, achieving a great leap from 'catching up with the times' to 'leading the times'.",
    "The establishment of the Communist Party of China, the founding of the People's Republic of China, and the advancement of reform, opening up, and the cause of socialism with Chinese characteristics are the three historic events that have occurred in China since the May Fourth Movement, and the three milestones on the path towards the great rejuvenation of the Chinese nation in modern times.",
    "China has maintained long-term overall social stability and has become one of the countries with the strongest sense of security in the world. The problems of hunger, inadequate food and clothing, and impoverished living that have plagued the Chinese people for millennia are generally gone for good!",
    "The achievements of the past 40 years were not handed down from heaven, nor were they gifts or charity from others; they were achieved through the hard work, wisdom, and courage of the entire Party and people of all ethnic groups! In just a few decades, we have completed the industrialization process that took developed countries several centuries. In the hands of the Chinese people, the impossible has become possible.",
    "Over the past 40 years of reform and opening up, the overarching theme of all our Party's theory and practice has been upholding and developing socialism with Chinese characteristics. In advancing reform and development in a large country like China, with a civilization history of over 5,000 years and a population of over 1.3 billion, there is no textbook that can be treated as an infallible golden rule, nor any teacher who can arrogantly dictate to the Chinese people.",
    "What to reform and how to reform must be fundamentally gauged by whether they serve the overarching goal of improving and developing the system of socialism with Chinese characteristics and modernizing China's system and capacity for governance. What should and can be reformed, we will resolutely reform; what should not and cannot be reformed, we will resolutely refrain from reforming.",
    "Achieving the complete reunification of the motherland is the common aspiration of all Chinese sons and daughters and the fundamental interest of the Chinese nation. We have the firm political resolve and strong capability to safeguard national sovereignty and territorial integrity; not a single inch of our sacred territory can be separated!",
    "Undertakings arise from careful planning, succeed through diligent execution, and fail due to arrogance. A great dream is not something to be waited for or shouted into existence, but something to be fought for and achieved through hard work. We are now at a point where the river current surges more fiercely midstream and the mountain path grows steeper halfway up—a stage where moving forward becomes increasingly difficult and perilous, yet failing to advance means retreating.",
    "Faith, conviction, and confidence are always of paramount importance. Be it an individual, a collective, a political party, a nation, or a country, with faith, conviction, and confidence, one will become more resilient through setbacks and braver in battle; otherwise, one will face defeat without fighting and collapse without a blow.",
    "Throughout the long historical process since modern times, the Chinese people have endured too many hardships, made too many sacrifices, and engaged in too many strenuous struggles. Now, the powerful energy accumulated by the Chinese people and the Chinese nation over this historical course has fully erupted, providing an unstoppable and majestic force for realizing the great rejuvenation of the Chinese nation.",
    "Building a great modern socialist country and realizing the great rejuvenation of the Chinese nation is a relay race. We must pass the baton from one generation to the next, each generation striving to run a good leg for the next.",
    "Socialism with Chinese characteristics did not fall from the sky. It was achieved through the great practice of 40 years of reform and opening up, through the continuous exploration over nearly 70 years since the founding of the People's Republic of China, through the practice of the great social revolution led by our Party and the people over 97 years, and represents the valuable gains made by the Party and the people through countless hardships and at various costs.",
    "To uphold and develop socialism with Chinese characteristics in the new era, we need a large cohort of talented people who can effectively tell the story of Marxism adapted to the Chinese context, using language the people understand and accept, enabling the Party's innovative theories to 'fly into the homes of ordinary people'.",
    "Staying true to our original aspiration and keeping our mission firmly in mind requires us to carry forward the fighting spirit and be courageous in shouldering responsibilities. Our Party was born amidst internal turmoil and external threats to the nation, at a time of national peril. From its very inception, the hallmark of struggle was etched upon it, and it has journeyed thus far through struggle to survive, develop, and achieve victory.",
    "The struggle we speak of is not struggle for struggle's sake, nor for personal gain, but to realize the people's yearning for a better life and the great rejuvenation of the Chinese nation, knowing the weight of responsibility, working hard and concretely, and overcoming difficulties.",
    "To gauge whether Party members and officials possess the fighting spirit and dare to shoulder responsibilities, we must examine whether they dare to draw their swords against major right and wrong issues, whether they dare to tackle difficulties head-on when facing conflicts, whether they dare to step forward in times of crisis, whether they dare to take responsibility for their mistakes, and whether they dare to resolutely combat unhealthy tendencies.",
    "With faith in one's heart, one can walk far. Facing the future and walking the Long March of the new era well, we must more firmly strengthen our ideals and convictions and be determined to strive and struggle.",
    "Practice tells us that all great undertakings begin with dreams. Dreams are the source of vitality. On the journey to build a great modern socialist country and realize the great rejuvenation of the Chinese nation, every industry and every individual must harbor dreams, strive courageously, step by step, baton after baton, achieving their dreams through vigorous effort and continuous struggle.",
    "There is no greater happiness in the world than striving for the people's well-being. With the people in our hearts, truth in our hands, and walking the path of righteousness, we are full of confidence and strength.",
    "The Chinese Dream is the common dream of compatriots on both sides of the Taiwan Strait. Only with national rejuvenation and a strong country can Chinese people on both sides live prosperous and beautiful lives. In the process of the great rejuvenation of the Chinese nation, our Taiwanese compatriots will certainly not be absent.",
    "Patriotism is the heart and soul of the Chinese nation. We must integrate the specific goals of our learning with the grand goal of national rejuvenation and strive for it. Only by integrating the small self into the greater whole can we possess minds as broad as the ocean and aspirations as lofty as the mountains.",
    "The promotion of integrated media development aims to strengthen mainstream public opinion, consolidate the common ideological foundation for the united struggle of the entire Party and people nationwide, and provide powerful spiritual strength and public opinion support for achieving the 'Two Centenary Goals' and the Chinese Dream of the great rejuvenation of the Chinese nation.",
    "The achievements and experience we have made in poverty alleviation and eradication have contributed Chinese wisdom and solutions to the global cause of poverty reduction, highlighting the political advantages of the leadership of the Communist Party of China and China's socialist system. Among developing countries, only China has achieved rapid development alongside large-scale poverty reduction simultaneously—a remarkable human miracle.",
    "Today, under the leadership of the Communist Party of China, we have blazed the path of socialism with Chinese characteristics, formed the theoretical system of socialism with Chinese characteristics, established the system of socialism with Chinese characteristics, developed socialist culture with Chinese characteristics, and propelled socialism with Chinese characteristics into a new era. The Chinese people now possess unprecedented confidence in their path, theory, system, and culture, and the great rejuvenation of the Chinese nation displays unprecedentedly bright prospects!",
    "As socialism with Chinese characteristics enters a new era, we are closer, more confident, and more capable than at any other time in history of realizing the great rejuvenation of the Chinese nation. Yet we must never lose our revolutionary spirit and fighting will amidst cheers and praise, slipping into a state of complacency, reluctance to progress, and pleasure-seeking. Rather, we must remember that midstream currents are fiercer and halfway up the mountain the path is steeper.",
    "We must guide people to establish correct views on history, the nation, ethnicity, and culture, and continuously consolidate the identification of people of all ethnic groups with our great motherland, the Chinese nation, and the path of socialism with Chinese characteristics.",
    "We must both firmly believe in the bright future of China's development and fully recognize the tortuous path and numerous difficulties ahead. We must leverage the political advantages of the leadership of the Communist Party of China and China's socialist system, concentrate our efforts on major tasks, fight a well-prepared battle to prevent and defuse risks, and wage a proactive strategic battle to turn peril into safety and crisis into opportunity.",
    "We must fully leverage the institutional advantage of concentrating efforts on major tasks and the advantage of our super-large-scale market to fight the tough battle of upgrading the industrial base and modernizing the industrial chain.",
    "The birth and development of Marxism and the birth and development of socialist countries are filled with arduous struggles. The establishment of the Communist Party of China, the founding of the People's Republic of China, the implementation of reform and opening up, and the advancement of the cause of socialism with Chinese characteristics for a new era have all been born, developed, and strengthened through struggle.",
    "Today's world is undergoing profound changes unseen in a century. The great struggle, great project, great cause, and great dream led by our Party are advancing vigorously. To successfully achieve the goals and tasks set by our Party, we must carry forward the fighting spirit and enhance our ability to struggle.",
    "Socialism with Chinese characteristics for a new era is the achievement of the great social revolution led by our Party and the people, and it is also the continuation of this great social revolution, which must be consistently carried forward. Achieving the final victory of a social revolution often requires a long historical process.",
    "The fundamental reason why China has been able to strongly advance epidemic prevention and control and the resumption of work and production is that the leadership of the Party and the advantages of China's socialist system have played an incomparably important role. The more severe and complex the development environment, the more we must unswervingly deepen reforms, improve systems in all respects, perfect the governance system, and be adept at using our institutional advantages to respond to risks, challenges, and shocks.",
    "The reason why our Party has been able to accomplish the arduous tasks that no other political force in modern times could accomplish, leading the people to brilliant achievements in revolution, construction, and reform, lies in its consistently taking Marxism as a guide to action and persistently arming the entire Party with the latest achievements in adapting Marxism to the Chinese context, thereby ensuring that the Party maintains unified thinking, firm will, coordinated action, and strong combat effectiveness.",
    "We must focus on improving the level of Marxist theory, studying deeply and understanding thoroughly, achieving mastery, grasping dialectical and historical materialism, mastering the Marxist stance, viewpoints, and methods running through them, mastering Sinicized Marxism, and being firm believers in and faithful practitioners of Marxism.",
    "Ideological and political theory courses must address students' problems with ideals and convictions. Let those with faith speak of faith. Faith in Marxism, and belief in socialism and communism, must first take root in the hearts of ideological and political theory teachers before they can blossom and bear fruit in the hearts of students.",
    "We must educate and guide students to read more classic Marxist works, contemporary Chinese Marxist theoretical works, and classics of fine traditional Chinese culture. We should provide reading lists and highlight key points, enabling students to correctly understand classic works, grasp the essence of Marxism, and perceive the charm of Chinese culture.",
    "A short rope cannot draw water from a deep well, and shallow water cannot bear a heavy boat. For leading officials, the strategic ability to grasp the overall situation and plan for development is extremely important. To develop and enhance this ability, one must comprehensively master the worldview and methodology of dialectical and historical materialism.",
    "We must organically combine classroom teaching with practical teaching, make full use of rich historical and cultural resources, closely relate to the struggles of the Communist Party of China and the Chinese people, deeply comprehend the inner logic of the Sinicization of Marxism, profoundly understand why history and the people chose the Communist Party of China and socialism, and further strengthen the 'Four Matters of Confidence.'",
    "Since the outbreak of the epidemic, the vast number of medical workers, including those from the military, have displayed a spirit of being particularly able to endure hardship and engage in combat, rushing to Hubei and Wuhan without hesitation, throwing themselves into prevention, control, and treatment without fear, racing against time, and battling the disease. You have truly lived up to the ideal of healing the wounded and rescuing the dying, showing boundless love. You are messengers of light and hope, the most beautiful angels, true heroes! The Party and the people thank you!",
    "Under the strong leadership of the Communist Party of China, by fully leveraging the advantages of the socialist system with Chinese characteristics, closely relying on the people, firming up confidence, uniting as one, adopting science-based prevention and targeted measures, we have full confidence and capability to win this battle against the epidemic.",
    "Ensuring the safety and health of the people is a major task of our Party in governing the country. This fight against the COVID-19 pandemic is a major test of the national governance system and capacity.",
    "We must vigorously promote the great spirit forged in the fight against the pandemic throughout society, transforming it into a powerful force for comprehensively building a modern socialist country and realizing the great rejuvenation of the Chinese nation.",
    "Both history and reality tell us that as long as we continuously unleash and develop social productive forces, continuously enhance our economic, scientific, technological, and comprehensive national strength, continuously enrich the people's sense of gain, happiness, and security, and continuously strengthen the material foundation for upholding and developing socialism with Chinese characteristics and realizing the great rejuvenation of the Chinese nation, we will surely be able to ensure that the ship of socialism with Chinese characteristics rides the wind and waves and sails steadily and far.",
    "Over the 75 years since the victory of the Chinese People's War of Resistance Against Japanese Aggression, China has undergone earth-shaking changes. The Communist Party of China has united and led the people of all ethnic groups across the country in working strenuously and starting from scratch, creating development achievements that have captured the world's attention, successfully blazing the path of socialism with Chinese characteristics. As socialism with Chinese characteristics enters a new era, victory is in sight in the battle against poverty and in building a moderately prosperous society in all respects, and the great rejuvenation of the Chinese nation has welcomed bright prospects.",
    "The Chinese people fostered a great spirit of resistance during the magnificent course of the War of Resistance, demonstrating to the world the patriotic sentiment that 'everyone is responsible for the fate of their country,' the national integrity of preferring death to dishonor, the heroic spirit of defying brute force and fighting to the end, and the indomitable conviction in victory. This great spirit of resistance is an invaluable spiritual treasure of the Chinese people and will forever inspire them to overcome all difficulties and obstacles and strive for the great rejuvenation of the Chinese nation.",
    "Today you are saplings, and in the future, you will grow into towering trees. The Chinese Dream of the great rejuvenation of the Chinese nation will be realized through you. I hope the students will carry forward the Red Gene, diligently study knowledge and skills, and strive to grow into socialist builders and successors who are well-rounded in moral, intellectual, physical, aesthetic, and labor education.",
    "Since the 18th National Congress of the CPC, with a view to realizing the Chinese Dream of the great rejuvenation of the Chinese nation and centering on achieving the Party's goal of building a strong military in the new era, we have put forward a series of major guiding principles and policies, made a series of major decisions and arrangements, and advanced a series of major work, ushering in a new phase in strengthening the armed forces.",
    "To promote the high-quality development of China's automobile manufacturing industry, we must strengthen independent research and development of key core technologies and key components, achieve technological self-reliance and self-improvement, and make our national brands bigger and stronger. In today's fiercely competitive global manufacturing landscape, we must seize opportunities and vigorously develop strategic emerging industries to achieve 'overtaking on curves.'",
    "To uphold and develop socialism with Chinese characteristics in the new era, we must fully implement the new development concept, adhere to the coordinated advancement of the 'Five-sphere Integrated Plan' and the 'Four-pronged Comprehensive Strategy', strengthen top-level design and strategic layout, and enhance the holistic and synergistic nature of development.",
    "Facing the new situation and new tasks, we must fully implement the Party's strategy for governing Tibet in the new era, forge a strong sense of community for the Chinese nation, improve the quality of development, safeguard and improve people's livelihoods, promote ecological progress, strengthen Party organization and governance capacity building, and ensure national security and lasting stability.",
    "The new situation calls for new responsibility and new actions. In constructing special economic zones in the new era, we must hold high the great banner of socialism with Chinese characteristics, proceed from the overall situation of China entering a new stage of development, implement the new development concept, closely focus on promoting high-quality development and constructing a new development paradigm, and with an indomitable spirit of struggle and a dauntless mental state, press ahead with reform and opening up non-stop from a higher starting point.",
    "To remember this great victory and advance our great cause, we must persist in promoting economic and social development and continuously strengthen our country's comprehensive national power. Backwardness leaves one vulnerable to attack; only development can make one strong. As long as we coordinate and advance the 'Five-sphere Integrated Plan' and the 'Four-pronged Comprehensive Strategy', unswervingly implement the new development concept, and build a new development paradigm, we will surely achieve higher quality, more efficient, more equitable, more sustainable, and safer development, continuously creating even greater miracles that amaze the world!",
    "Since the 18th National Congress of the CPC, our Party's thinking on ecological civilization has been continuously enriched and improved. Ecological civilization construction is a part of the 'Five-sphere Integrated Plan'; harmony between humanity and nature is a fundamental principle in the basic policy for upholding and developing socialism with Chinese characteristics in the new era; green development is one of the key concepts in the new development philosophy; and pollution prevention and control is one of the 'three critical battles.'",
    "Implementing the strategy of expanding domestic demand is necessary to cope with the impact of the pandemic at present, to maintain the long-term, sustained, and healthy development of China's economy, and to meet the people's growing needs for a better life.",
    "Consumption is an important engine for China's economic growth, and the middle-income group is an important foundation for consumption. Currently, China has about 400 million middle-income earners, the largest such population in absolute terms in the world. We should set expanding the middle-income group's size as an important policy goal, enabling more ordinary workers to join this group through their own efforts.",
    "Manufacturing is the lifeblood of a nation's economy. Large state-owned enterprises must play a leading role, driving the comprehensive resumption of work and production across upstream and downstream industries and for small and medium-sized enterprises, under the premise of effectively implementing routine epidemic prevention measures.",
    "For a long time, Shanxi has been both blessed and trapped by coal, with the dominance of coal leading to a single-industry structure. Building a demonstration zone for comprehensive transformation and reform is a major task entrusted to Shanxi by the Party Central Committee. Shanxi must have a sense of urgency and, more importantly, a long-term strategic plan. It must persist in the right course with sustained effort over time, avoiding reversals and turmoil, striving to blaze a new path for transformation and development as soon as possible.",
    "We must more promptly and effectively solve the various difficulties and problems faced by enterprises in resuming production and operations, effectively implement various policies and measures to expand domestic demand, strengthen and optimize the real economy, especially manufacturing, continue to promote industrial structure adjustment and optimization, vigorously enhance scientific and technological innovation, and continuously achieve breakthroughs in new infrastructure, new technologies, new materials, new equipment, new products, and new business forms.",
    "We will adhere to the One-China Principle and the '1992 Consensus', consolidate and develop the foundation for the peaceful development of cross-strait relations, and deepen cross-strait economic and cultural exchanges and cooperation for the benefit of compatriots on both sides. The Taiwan issue arose from national weakness and turmoil and will surely end with national rejuvenation!",
    "Under the current circumstances, to successfully deliver ideological and political theory courses, we must approach them from the strategic height of upholding and developing socialism with Chinese characteristics, building a great modern socialist country, and realizing the great rejuvenation of the Chinese nation. Our Party, committed to the millennia-long cause of the Chinese nation, must cultivate generation after generation of capable talents who support the leadership of the Communist Party of China and China's socialist system and are determined to devote their lives to the cause of socialism with Chinese characteristics.",
    "The most fundamental task in delivering ideological and political theory courses is to comprehensively implement the Party's education policy and address the fundamental questions of what kind of people to cultivate, how to cultivate them, and for whom to cultivate them. We must uphold the guiding position of Marxism, implement the Thought on Socialism with Chinese Characteristics for a New Era, adhere to the socialist direction of education, fulfill the fundamental task of fostering virtue through education, strive to cultivate a new generation capable of shouldering the great task of national rejuvenation, and train socialist builders and successors who are well-rounded in moral, intellectual, physical, aesthetic, and labor education.",
    "This year marks the 70th anniversary of the founding of the People's Republic of China. Adhering to the leadership of the Communist Party of China is the historical choice of the Chinese people. Over the past 70 years, under the CPC's leadership, the Chinese people have continuously strived and achieved tremendous accomplishments in all respects. When China manages its own affairs well, it is a contribution to the world.",
    "We must be adept at transforming the leadership of the Party and the strengths of China's socialist system into the effectiveness of national governance, improving the social governance system featuring Party committee leadership, government responsibility, social coordination, public participation, and legal guarantee, and fostering a social governance pattern based on collaboration, participation, and common interests.",
    "The political and legal system must, from a higher starting point, push for new breakthroughs in reform and accelerate the establishment of an optimized, coordinated, and efficient functional system for political and legal institutions. We must fully implement the judicial accountability system, allowing judicial personnel to concentrate on performing their duties and handling cases properly, thereby improving judicial quality, efficiency, and credibility.",
    "We must seek impetus from reform and innovation, playing an important role as a driving force in leading high-quality development. We need to gather and utilize high-end innovation resources, actively engage in major scientific and technological project R&D cooperation, and build an important source of indigenous innovation and a primary wellspring of original innovation in China.",
    "The Chinese nation is at a critical period for its great rejuvenation, and our reform and development efforts are at a crucial stage where we must overcome difficulties and break through barriers. There is an urgent need for officials who are enterprising, energetic, and able to withstand pressure at critical moments.",
    "We need to deepen our understanding of the international and domestic financial situation, correctly grasp the essence of finance, deepen supply-side structural reform in the financial sector, balance the relationship between stabilizing growth and preventing risks, precisely and effectively address risks in key areas, deepen financial reform and opening up, enhance the financial sector's ability to serve the real economy, resolutely fight the tough battle of preventing and defusing major risks including financial risks, and promote the healthy development of China's financial industry.",
    "The economy and society are a dynamic circulatory system that cannot be shut down for long. On the premise of ensuring adequate epidemic prevention and control, promoting the resumption of work and production for enterprises and institutions in non-key epidemic control areas and restoring the order of production and daily life is crucial for providing strong material support for epidemic prevention and control, ensuring people's livelihoods and social stability, and achieving the year's economic and social development goals.",
  ]
};
